export interface CountryConfig {
  code: string;
  name: string;
  currency: string;
  timezone: string;
  dateFormat: string;
}

export const COUNTRY_CONFIGS: CountryConfig[] = [
  {
    code: "US",
    name: "United States",
    currency: "USD",
    timezone: "America/New_York",
    dateFormat: "MM/DD/YYYY",
  },
  {
    code: "GB",
    name: "United Kingdom",
    currency: "GBP",
    timezone: "Europe/London",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "CA",
    name: "Canada",
    currency: "CAD",
    timezone: "America/Toronto",
    dateFormat: "YYYY-MM-DD",
  },
  {
    code: "AU",
    name: "Australia",
    currency: "AUD",
    timezone: "Australia/Sydney",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "NZ",
    name: "New Zealand",
    currency: "NZD",
    timezone: "Pacific/Auckland",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "IE",
    name: "Ireland",
    currency: "EUR",
    timezone: "Europe/Dublin",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "ZA",
    name: "South Africa",
    currency: "ZAR",
    timezone: "Africa/Johannesburg",
    dateFormat: "YYYY/MM/DD",
  },
  {
    code: "NG",
    name: "Nigeria",
    currency: "NGN",
    timezone: "Africa/Lagos",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "KE",
    name: "Kenya",
    currency: "KES",
    timezone: "Africa/Nairobi",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "GH",
    name: "Ghana",
    currency: "GHS",
    timezone: "Africa/Accra",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    currency: "AED",
    timezone: "Asia/Dubai",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    currency: "SAR",
    timezone: "Asia/Riyadh",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "IN",
    name: "India",
    currency: "INR",
    timezone: "Asia/Kolkata",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "PK",
    name: "Pakistan",
    currency: "PKR",
    timezone: "Asia/Karachi",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "BD",
    name: "Bangladesh",
    currency: "BDT",
    timezone: "Asia/Dhaka",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "MY",
    name: "Malaysia",
    currency: "MYR",
    timezone: "Asia/Kuala_Lumpur",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "ID",
    name: "Indonesia",
    currency: "IDR",
    timezone: "Asia/Jakarta",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "SG",
    name: "Singapore",
    currency: "SGD",
    timezone: "Asia/Singapore",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "PH",
    name: "Philippines",
    currency: "PHP",
    timezone: "Asia/Manila",
    dateFormat: "MM/DD/YYYY",
  },
  {
    code: "DE",
    name: "Germany",
    currency: "EUR",
    timezone: "Europe/Berlin",
    dateFormat: "DD.MM.YYYY",
  },
  {
    code: "FR",
    name: "France",
    currency: "EUR",
    timezone: "Europe/Paris",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "IT",
    name: "Italy",
    currency: "EUR",
    timezone: "Europe/Rome",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "ES",
    name: "Spain",
    currency: "EUR",
    timezone: "Europe/Madrid",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "NL",
    name: "Netherlands",
    currency: "EUR",
    timezone: "Europe/Amsterdam",
    dateFormat: "DD-MM-YYYY",
  },
  {
    code: "SE",
    name: "Sweden",
    currency: "SEK",
    timezone: "Europe/Stockholm",
    dateFormat: "YYYY-MM-DD",
  },
  {
    code: "NO",
    name: "Norway",
    currency: "NOK",
    timezone: "Europe/Oslo",
    dateFormat: "DD.MM.YYYY",
  },
  {
    code: "DK",
    name: "Denmark",
    currency: "DKK",
    timezone: "Europe/Copenhagen",
    dateFormat: "DD-MM-YYYY",
  },
  {
    code: "BR",
    name: "Brazil",
    currency: "BRL",
    timezone: "America/Sao_Paulo",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "MX",
    name: "Mexico",
    currency: "MXN",
    timezone: "America/Mexico_City",
    dateFormat: "DD/MM/YYYY",
  },
  {
    code: "AR",
    name: "Argentina",
    currency: "ARS",
    timezone: "America/Argentina/Buenos_Aires",
    dateFormat: "DD/MM/YYYY",
  },
];

export const TIMEZONES = [
  "America/New_York",
  "America/Chicago",
  "America/Denver",
  "America/Los_Angeles",
  "America/Anchorage",
  "Pacific/Honolulu",
  "Europe/London",
  "Europe/Paris",
  "Europe/Berlin",
  "Europe/Rome",
  "Europe/Madrid",
  "Europe/Amsterdam",
  "Europe/Stockholm",
  "Europe/Oslo",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Asia/Dubai",
  "Asia/Riyadh",
  "Asia/Kolkata",
  "Asia/Karachi",
  "Asia/Dhaka",
  "Asia/Kuala_Lumpur",
  "Asia/Jakarta",
  "Asia/Singapore",
  "Asia/Manila",
  "Asia/Tokyo",
  "Asia/Shanghai",
  "Asia/Hong_Kong",
  "Australia/Sydney",
  "Australia/Melbourne",
  "Australia/Brisbane",
  "Australia/Perth",
  "Pacific/Auckland",
  "Africa/Johannesburg",
  "Africa/Lagos",
  "Africa/Nairobi",
  "Africa/Accra",
  "Africa/Cairo",
  "America/Toronto",
  "America/Vancouver",
  "America/Sao_Paulo",
  "America/Mexico_City",
  "America/Argentina/Buenos_Aires",
];

export const CURRENCIES = [
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "CAD", name: "Canadian Dollar", symbol: "CA$" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "GH₵" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "MXN", name: "Mexican Peso", symbol: "MX$" },
  { code: "ARS", name: "Argentine Peso", symbol: "$" },
];

export const DATE_FORMATS = [
  { format: "MM/DD/YYYY", example: "12/31/2024", label: "MM/DD/YYYY (US)" },
  { format: "DD/MM/YYYY", example: "31/12/2024", label: "DD/MM/YYYY (UK, EU)" },
  { format: "YYYY-MM-DD", example: "2024-12-31", label: "YYYY-MM-DD (ISO)" },
  { format: "DD.MM.YYYY", example: "31.12.2024", label: "DD.MM.YYYY (DE)" },
  { format: "DD-MM-YYYY", example: "31-12-2024", label: "DD-MM-YYYY (NL)" },
  { format: "YYYY/MM/DD", example: "2024/12/31", label: "YYYY/MM/DD (ZA)" },
];

export function getCountryConfig(countryCode: string): CountryConfig | undefined {
  return COUNTRY_CONFIGS.find((c) => c.code === countryCode);
}

export function getCurrencySymbol(currencyCode: string): string {
  const currency = CURRENCIES.find((c) => c.code === currencyCode);
  return currency?.symbol || currencyCode;
}
